runtime: python311  # latest second-gen runtime
entrypoint: gunicorn -b :$PORT main:app

instance_class: F1  # still free within quota

automatic_scaling:
  max_instances: 1

env_variables:
  GOOGLE_CLOUD_PROJECT: "lapleaderboard"
  FIRESTORE_EMULATOR_HOST: ""
  ALLOWED_ADMINS: "finlaywojtan@gmail.com"
